# Generated by Django 5.0.12 on 2025-03-20 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_user_for_anonymous_contributors(apps, schema_editor):
    """
    Set the user field to None for all contributors with is_anonymous=True.
    """
    Contributor = apps.get_model("scipost", "Contributor")
    Contributor.objects.filter(is_anonymous=True).update(dbuser=None)


def delete_contributors_without_user(apps, schema_editor):
    """
    Delete all contributors without a user.
    """
    Contributor = apps.get_model("scipost", "Contributor")
    Contributor.objects.filter(dbuser=None).delete()

    try:
        # Attempt to delete any anonymous contributors
        AnonymousContributor = apps.get_model("anonymization", "AnonymousContributor")
        AnonymousContributor.objects.delete()
    except Exception:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("scipost", "0042_contributor_is_anonymous"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor",
            old_name="user",
            new_name="dbuser",
        ),
        migrations.AlterField(
            model_name="contributor",
            name="dbuser",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.RunPython(
            delete_user_for_anonymous_contributors, delete_contributors_without_user
        ),
        migrations.AlterModelOptions(
            name="contributor",
            options={"ordering": ["dbuser__last_name", "dbuser__first_name"]},
        ),
    ]
